lm_decoder:
  enabled: false
  runtime_root: ${hydra:runtime.cwd}/third_party/speechBCI/runtime/server/x86
  auto_download: false
  resource:
    fst_path: ""
    const_arpa_path: ""
    g_path: ""
    words_path: ""
    symbol_table: ""
  decode_options:
    max_active: 7000
    min_active: 200
    beam: 17.0
    lattice_beam: 8.0
    acoustic_scale: 1.0
    ctc_blank_skip_threshold: 0.98
    nbest: 10
  logit_mapping: null

fusion:
  enabled: false
  beam_width: 10
  beam_search_width: 10
  fusion_weight: 0.3
  temperature: 1.0
  length_penalty: 0.0
  lm_model: null
  tokenizer: null
  device: auto
  log_metric: val/lm_cer
